# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/edav/devel/cpp-work/AC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/edav/devel/cpp-work/AC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edav/devel/cpp-work/AC/CMakeFiles /home/edav/devel/cpp-work/AC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edav/devel/cpp-work/AC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean-enet

# Build rule for target.
clean-enet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean-enet
.PHONY : clean-enet

# fast build rule for target.
clean-enet/fast:
	$(MAKE) -f CMakeFiles/clean-enet.dir/build.make CMakeFiles/clean-enet.dir/build
.PHONY : clean-enet/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named enet

# Build rule for target.
enet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enet
.PHONY : enet

# fast build rule for target.
enet/fast:
	$(MAKE) -f CMakeFiles/enet.dir/build.make CMakeFiles/enet.dir/build
.PHONY : enet/fast

#=============================================================================
# Target rules for targets named enet-config

# Build rule for target.
enet-config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enet-config
.PHONY : enet-config

# fast build rule for target.
enet-config/fast:
	$(MAKE) -f CMakeFiles/enet-config.dir/build.make CMakeFiles/enet-config.dir/build
.PHONY : enet-config/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

source/src/audiomanager.o: source/src/audiomanager.cpp.o

.PHONY : source/src/audiomanager.o

# target to build an object file
source/src/audiomanager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/audiomanager.cpp.o
.PHONY : source/src/audiomanager.cpp.o

source/src/audiomanager.i: source/src/audiomanager.cpp.i

.PHONY : source/src/audiomanager.i

# target to preprocess a source file
source/src/audiomanager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/audiomanager.cpp.i
.PHONY : source/src/audiomanager.cpp.i

source/src/audiomanager.s: source/src/audiomanager.cpp.s

.PHONY : source/src/audiomanager.s

# target to generate assembly for a file
source/src/audiomanager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/audiomanager.cpp.s
.PHONY : source/src/audiomanager.cpp.s

source/src/bot/ac_bot.o: source/src/bot/ac_bot.cpp.o

.PHONY : source/src/bot/ac_bot.o

# target to build an object file
source/src/bot/ac_bot.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/ac_bot.cpp.o
.PHONY : source/src/bot/ac_bot.cpp.o

source/src/bot/ac_bot.i: source/src/bot/ac_bot.cpp.i

.PHONY : source/src/bot/ac_bot.i

# target to preprocess a source file
source/src/bot/ac_bot.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/ac_bot.cpp.i
.PHONY : source/src/bot/ac_bot.cpp.i

source/src/bot/ac_bot.s: source/src/bot/ac_bot.cpp.s

.PHONY : source/src/bot/ac_bot.s

# target to generate assembly for a file
source/src/bot/ac_bot.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/ac_bot.cpp.s
.PHONY : source/src/bot/ac_bot.cpp.s

source/src/bot/ac_bot_ai.o: source/src/bot/ac_bot_ai.cpp.o

.PHONY : source/src/bot/ac_bot_ai.o

# target to build an object file
source/src/bot/ac_bot_ai.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/ac_bot_ai.cpp.o
.PHONY : source/src/bot/ac_bot_ai.cpp.o

source/src/bot/ac_bot_ai.i: source/src/bot/ac_bot_ai.cpp.i

.PHONY : source/src/bot/ac_bot_ai.i

# target to preprocess a source file
source/src/bot/ac_bot_ai.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/ac_bot_ai.cpp.i
.PHONY : source/src/bot/ac_bot_ai.cpp.i

source/src/bot/ac_bot_ai.s: source/src/bot/ac_bot_ai.cpp.s

.PHONY : source/src/bot/ac_bot_ai.s

# target to generate assembly for a file
source/src/bot/ac_bot_ai.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/ac_bot_ai.cpp.s
.PHONY : source/src/bot/ac_bot_ai.cpp.s

source/src/bot/bot.o: source/src/bot/bot.cpp.o

.PHONY : source/src/bot/bot.o

# target to build an object file
source/src/bot/bot.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot.cpp.o
.PHONY : source/src/bot/bot.cpp.o

source/src/bot/bot.i: source/src/bot/bot.cpp.i

.PHONY : source/src/bot/bot.i

# target to preprocess a source file
source/src/bot/bot.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot.cpp.i
.PHONY : source/src/bot/bot.cpp.i

source/src/bot/bot.s: source/src/bot/bot.cpp.s

.PHONY : source/src/bot/bot.s

# target to generate assembly for a file
source/src/bot/bot.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot.cpp.s
.PHONY : source/src/bot/bot.cpp.s

source/src/bot/bot_ai.o: source/src/bot/bot_ai.cpp.o

.PHONY : source/src/bot/bot_ai.o

# target to build an object file
source/src/bot/bot_ai.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_ai.cpp.o
.PHONY : source/src/bot/bot_ai.cpp.o

source/src/bot/bot_ai.i: source/src/bot/bot_ai.cpp.i

.PHONY : source/src/bot/bot_ai.i

# target to preprocess a source file
source/src/bot/bot_ai.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_ai.cpp.i
.PHONY : source/src/bot/bot_ai.cpp.i

source/src/bot/bot_ai.s: source/src/bot/bot_ai.cpp.s

.PHONY : source/src/bot/bot_ai.s

# target to generate assembly for a file
source/src/bot/bot_ai.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_ai.cpp.s
.PHONY : source/src/bot/bot_ai.cpp.s

source/src/bot/bot_util.o: source/src/bot/bot_util.cpp.o

.PHONY : source/src/bot/bot_util.o

# target to build an object file
source/src/bot/bot_util.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_util.cpp.o
.PHONY : source/src/bot/bot_util.cpp.o

source/src/bot/bot_util.i: source/src/bot/bot_util.cpp.i

.PHONY : source/src/bot/bot_util.i

# target to preprocess a source file
source/src/bot/bot_util.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_util.cpp.i
.PHONY : source/src/bot/bot_util.cpp.i

source/src/bot/bot_util.s: source/src/bot/bot_util.cpp.s

.PHONY : source/src/bot/bot_util.s

# target to generate assembly for a file
source/src/bot/bot_util.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_util.cpp.s
.PHONY : source/src/bot/bot_util.cpp.s

source/src/bot/bot_waypoint.o: source/src/bot/bot_waypoint.cpp.o

.PHONY : source/src/bot/bot_waypoint.o

# target to build an object file
source/src/bot/bot_waypoint.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_waypoint.cpp.o
.PHONY : source/src/bot/bot_waypoint.cpp.o

source/src/bot/bot_waypoint.i: source/src/bot/bot_waypoint.cpp.i

.PHONY : source/src/bot/bot_waypoint.i

# target to preprocess a source file
source/src/bot/bot_waypoint.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_waypoint.cpp.i
.PHONY : source/src/bot/bot_waypoint.cpp.i

source/src/bot/bot_waypoint.s: source/src/bot/bot_waypoint.cpp.s

.PHONY : source/src/bot/bot_waypoint.s

# target to generate assembly for a file
source/src/bot/bot_waypoint.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/bot_waypoint.cpp.s
.PHONY : source/src/bot/bot_waypoint.cpp.s

source/src/bot/botmanager.o: source/src/bot/botmanager.cpp.o

.PHONY : source/src/bot/botmanager.o

# target to build an object file
source/src/bot/botmanager.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/botmanager.cpp.o
.PHONY : source/src/bot/botmanager.cpp.o

source/src/bot/botmanager.i: source/src/bot/botmanager.cpp.i

.PHONY : source/src/bot/botmanager.i

# target to preprocess a source file
source/src/bot/botmanager.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/botmanager.cpp.i
.PHONY : source/src/bot/botmanager.cpp.i

source/src/bot/botmanager.s: source/src/bot/botmanager.cpp.s

.PHONY : source/src/bot/botmanager.s

# target to generate assembly for a file
source/src/bot/botmanager.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/bot/botmanager.cpp.s
.PHONY : source/src/bot/botmanager.cpp.s

source/src/client.o: source/src/client.cpp.o

.PHONY : source/src/client.o

# target to build an object file
source/src/client.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/client.cpp.o
.PHONY : source/src/client.cpp.o

source/src/client.i: source/src/client.cpp.i

.PHONY : source/src/client.i

# target to preprocess a source file
source/src/client.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/client.cpp.i
.PHONY : source/src/client.cpp.i

source/src/client.s: source/src/client.cpp.s

.PHONY : source/src/client.s

# target to generate assembly for a file
source/src/client.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/client.cpp.s
.PHONY : source/src/client.cpp.s

source/src/clientgame.o: source/src/clientgame.cpp.o

.PHONY : source/src/clientgame.o

# target to build an object file
source/src/clientgame.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/clientgame.cpp.o
.PHONY : source/src/clientgame.cpp.o

source/src/clientgame.i: source/src/clientgame.cpp.i

.PHONY : source/src/clientgame.i

# target to preprocess a source file
source/src/clientgame.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/clientgame.cpp.i
.PHONY : source/src/clientgame.cpp.i

source/src/clientgame.s: source/src/clientgame.cpp.s

.PHONY : source/src/clientgame.s

# target to generate assembly for a file
source/src/clientgame.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/clientgame.cpp.s
.PHONY : source/src/clientgame.cpp.s

source/src/clients2c.o: source/src/clients2c.cpp.o

.PHONY : source/src/clients2c.o

# target to build an object file
source/src/clients2c.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/clients2c.cpp.o
.PHONY : source/src/clients2c.cpp.o

source/src/clients2c.i: source/src/clients2c.cpp.i

.PHONY : source/src/clients2c.i

# target to preprocess a source file
source/src/clients2c.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/clients2c.cpp.i
.PHONY : source/src/clients2c.cpp.i

source/src/clients2c.s: source/src/clients2c.cpp.s

.PHONY : source/src/clients2c.s

# target to generate assembly for a file
source/src/clients2c.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/clients2c.cpp.s
.PHONY : source/src/clients2c.cpp.s

source/src/command.o: source/src/command.cpp.o

.PHONY : source/src/command.o

# target to build an object file
source/src/command.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/command.cpp.o
.PHONY : source/src/command.cpp.o

source/src/command.i: source/src/command.cpp.i

.PHONY : source/src/command.i

# target to preprocess a source file
source/src/command.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/command.cpp.i
.PHONY : source/src/command.cpp.i

source/src/command.s: source/src/command.cpp.s

.PHONY : source/src/command.s

# target to generate assembly for a file
source/src/command.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/command.cpp.s
.PHONY : source/src/command.cpp.s

source/src/console.o: source/src/console.cpp.o

.PHONY : source/src/console.o

# target to build an object file
source/src/console.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/console.cpp.o
.PHONY : source/src/console.cpp.o

source/src/console.i: source/src/console.cpp.i

.PHONY : source/src/console.i

# target to preprocess a source file
source/src/console.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/console.cpp.i
.PHONY : source/src/console.cpp.i

source/src/console.s: source/src/console.cpp.s

.PHONY : source/src/console.s

# target to generate assembly for a file
source/src/console.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/console.cpp.s
.PHONY : source/src/console.cpp.s

source/src/crypto.o: source/src/crypto.cpp.o

.PHONY : source/src/crypto.o

# target to build an object file
source/src/crypto.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/crypto.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/crypto.cpp.o
.PHONY : source/src/crypto.cpp.o

source/src/crypto.i: source/src/crypto.cpp.i

.PHONY : source/src/crypto.i

# target to preprocess a source file
source/src/crypto.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/crypto.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/crypto.cpp.i
.PHONY : source/src/crypto.cpp.i

source/src/crypto.s: source/src/crypto.cpp.s

.PHONY : source/src/crypto.s

# target to generate assembly for a file
source/src/crypto.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/crypto.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/crypto.cpp.s
.PHONY : source/src/crypto.cpp.s

source/src/docs.o: source/src/docs.cpp.o

.PHONY : source/src/docs.o

# target to build an object file
source/src/docs.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/docs.cpp.o
.PHONY : source/src/docs.cpp.o

source/src/docs.i: source/src/docs.cpp.i

.PHONY : source/src/docs.i

# target to preprocess a source file
source/src/docs.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/docs.cpp.i
.PHONY : source/src/docs.cpp.i

source/src/docs.s: source/src/docs.cpp.s

.PHONY : source/src/docs.s

# target to generate assembly for a file
source/src/docs.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/docs.cpp.s
.PHONY : source/src/docs.cpp.s

source/src/dummy.o: source/src/dummy.cpp.o

.PHONY : source/src/dummy.o

# target to build an object file
source/src/dummy.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/dummy.cpp.o
.PHONY : source/src/dummy.cpp.o

source/src/dummy.i: source/src/dummy.cpp.i

.PHONY : source/src/dummy.i

# target to preprocess a source file
source/src/dummy.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/dummy.cpp.i
.PHONY : source/src/dummy.cpp.i

source/src/dummy.s: source/src/dummy.cpp.s

.PHONY : source/src/dummy.s

# target to generate assembly for a file
source/src/dummy.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/dummy.cpp.s
.PHONY : source/src/dummy.cpp.s

source/src/editing.o: source/src/editing.cpp.o

.PHONY : source/src/editing.o

# target to build an object file
source/src/editing.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/editing.cpp.o
.PHONY : source/src/editing.cpp.o

source/src/editing.i: source/src/editing.cpp.i

.PHONY : source/src/editing.i

# target to preprocess a source file
source/src/editing.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/editing.cpp.i
.PHONY : source/src/editing.cpp.i

source/src/editing.s: source/src/editing.cpp.s

.PHONY : source/src/editing.s

# target to generate assembly for a file
source/src/editing.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/editing.cpp.s
.PHONY : source/src/editing.cpp.s

source/src/entities.o: source/src/entities.cpp.o

.PHONY : source/src/entities.o

# target to build an object file
source/src/entities.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/entities.cpp.o
.PHONY : source/src/entities.cpp.o

source/src/entities.i: source/src/entities.cpp.i

.PHONY : source/src/entities.i

# target to preprocess a source file
source/src/entities.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/entities.cpp.i
.PHONY : source/src/entities.cpp.i

source/src/entities.s: source/src/entities.cpp.s

.PHONY : source/src/entities.s

# target to generate assembly for a file
source/src/entities.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/entities.cpp.s
.PHONY : source/src/entities.cpp.s

source/src/geom.o: source/src/geom.cpp.o

.PHONY : source/src/geom.o

# target to build an object file
source/src/geom.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/geom.cpp.o
.PHONY : source/src/geom.cpp.o

source/src/geom.i: source/src/geom.cpp.i

.PHONY : source/src/geom.i

# target to preprocess a source file
source/src/geom.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/geom.cpp.i
.PHONY : source/src/geom.cpp.i

source/src/geom.s: source/src/geom.cpp.s

.PHONY : source/src/geom.s

# target to generate assembly for a file
source/src/geom.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/geom.cpp.s
.PHONY : source/src/geom.cpp.s

source/src/i18n.o: source/src/i18n.cpp.o

.PHONY : source/src/i18n.o

# target to build an object file
source/src/i18n.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/i18n.cpp.o
.PHONY : source/src/i18n.cpp.o

source/src/i18n.i: source/src/i18n.cpp.i

.PHONY : source/src/i18n.i

# target to preprocess a source file
source/src/i18n.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/i18n.cpp.i
.PHONY : source/src/i18n.cpp.i

source/src/i18n.s: source/src/i18n.cpp.s

.PHONY : source/src/i18n.s

# target to generate assembly for a file
source/src/i18n.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/i18n.cpp.s
.PHONY : source/src/i18n.cpp.s

source/src/jpegenc.o: source/src/jpegenc.cpp.o

.PHONY : source/src/jpegenc.o

# target to build an object file
source/src/jpegenc.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/jpegenc.cpp.o
.PHONY : source/src/jpegenc.cpp.o

source/src/jpegenc.i: source/src/jpegenc.cpp.i

.PHONY : source/src/jpegenc.i

# target to preprocess a source file
source/src/jpegenc.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/jpegenc.cpp.i
.PHONY : source/src/jpegenc.cpp.i

source/src/jpegenc.s: source/src/jpegenc.cpp.s

.PHONY : source/src/jpegenc.s

# target to generate assembly for a file
source/src/jpegenc.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/jpegenc.cpp.s
.PHONY : source/src/jpegenc.cpp.s

source/src/log.o: source/src/log.cpp.o

.PHONY : source/src/log.o

# target to build an object file
source/src/log.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/log.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/log.cpp.o
.PHONY : source/src/log.cpp.o

source/src/log.i: source/src/log.cpp.i

.PHONY : source/src/log.i

# target to preprocess a source file
source/src/log.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/log.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/log.cpp.i
.PHONY : source/src/log.cpp.i

source/src/log.s: source/src/log.cpp.s

.PHONY : source/src/log.s

# target to generate assembly for a file
source/src/log.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/log.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/log.cpp.s
.PHONY : source/src/log.cpp.s

source/src/main.o: source/src/main.cpp.o

.PHONY : source/src/main.o

# target to build an object file
source/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/main.cpp.o
.PHONY : source/src/main.cpp.o

source/src/main.i: source/src/main.cpp.i

.PHONY : source/src/main.i

# target to preprocess a source file
source/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/main.cpp.i
.PHONY : source/src/main.cpp.i

source/src/main.s: source/src/main.cpp.s

.PHONY : source/src/main.s

# target to generate assembly for a file
source/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/main.cpp.s
.PHONY : source/src/main.cpp.s

source/src/menus.o: source/src/menus.cpp.o

.PHONY : source/src/menus.o

# target to build an object file
source/src/menus.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/menus.cpp.o
.PHONY : source/src/menus.cpp.o

source/src/menus.i: source/src/menus.cpp.i

.PHONY : source/src/menus.i

# target to preprocess a source file
source/src/menus.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/menus.cpp.i
.PHONY : source/src/menus.cpp.i

source/src/menus.s: source/src/menus.cpp.s

.PHONY : source/src/menus.s

# target to generate assembly for a file
source/src/menus.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/menus.cpp.s
.PHONY : source/src/menus.cpp.s

source/src/physics.o: source/src/physics.cpp.o

.PHONY : source/src/physics.o

# target to build an object file
source/src/physics.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/physics.cpp.o
.PHONY : source/src/physics.cpp.o

source/src/physics.i: source/src/physics.cpp.i

.PHONY : source/src/physics.i

# target to preprocess a source file
source/src/physics.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/physics.cpp.i
.PHONY : source/src/physics.cpp.i

source/src/physics.s: source/src/physics.cpp.s

.PHONY : source/src/physics.s

# target to generate assembly for a file
source/src/physics.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/physics.cpp.s
.PHONY : source/src/physics.cpp.s

source/src/protocol.o: source/src/protocol.cpp.o

.PHONY : source/src/protocol.o

# target to build an object file
source/src/protocol.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/protocol.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/protocol.cpp.o
.PHONY : source/src/protocol.cpp.o

source/src/protocol.i: source/src/protocol.cpp.i

.PHONY : source/src/protocol.i

# target to preprocess a source file
source/src/protocol.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/protocol.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/protocol.cpp.i
.PHONY : source/src/protocol.cpp.i

source/src/protocol.s: source/src/protocol.cpp.s

.PHONY : source/src/protocol.s

# target to generate assembly for a file
source/src/protocol.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/protocol.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/protocol.cpp.s
.PHONY : source/src/protocol.cpp.s

source/src/rendercubes.o: source/src/rendercubes.cpp.o

.PHONY : source/src/rendercubes.o

# target to build an object file
source/src/rendercubes.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendercubes.cpp.o
.PHONY : source/src/rendercubes.cpp.o

source/src/rendercubes.i: source/src/rendercubes.cpp.i

.PHONY : source/src/rendercubes.i

# target to preprocess a source file
source/src/rendercubes.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendercubes.cpp.i
.PHONY : source/src/rendercubes.cpp.i

source/src/rendercubes.s: source/src/rendercubes.cpp.s

.PHONY : source/src/rendercubes.s

# target to generate assembly for a file
source/src/rendercubes.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendercubes.cpp.s
.PHONY : source/src/rendercubes.cpp.s

source/src/rendergl.o: source/src/rendergl.cpp.o

.PHONY : source/src/rendergl.o

# target to build an object file
source/src/rendergl.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendergl.cpp.o
.PHONY : source/src/rendergl.cpp.o

source/src/rendergl.i: source/src/rendergl.cpp.i

.PHONY : source/src/rendergl.i

# target to preprocess a source file
source/src/rendergl.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendergl.cpp.i
.PHONY : source/src/rendergl.cpp.i

source/src/rendergl.s: source/src/rendergl.cpp.s

.PHONY : source/src/rendergl.s

# target to generate assembly for a file
source/src/rendergl.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendergl.cpp.s
.PHONY : source/src/rendergl.cpp.s

source/src/renderhud.o: source/src/renderhud.cpp.o

.PHONY : source/src/renderhud.o

# target to build an object file
source/src/renderhud.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/renderhud.cpp.o
.PHONY : source/src/renderhud.cpp.o

source/src/renderhud.i: source/src/renderhud.cpp.i

.PHONY : source/src/renderhud.i

# target to preprocess a source file
source/src/renderhud.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/renderhud.cpp.i
.PHONY : source/src/renderhud.cpp.i

source/src/renderhud.s: source/src/renderhud.cpp.s

.PHONY : source/src/renderhud.s

# target to generate assembly for a file
source/src/renderhud.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/renderhud.cpp.s
.PHONY : source/src/renderhud.cpp.s

source/src/rendermodel.o: source/src/rendermodel.cpp.o

.PHONY : source/src/rendermodel.o

# target to build an object file
source/src/rendermodel.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendermodel.cpp.o
.PHONY : source/src/rendermodel.cpp.o

source/src/rendermodel.i: source/src/rendermodel.cpp.i

.PHONY : source/src/rendermodel.i

# target to preprocess a source file
source/src/rendermodel.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendermodel.cpp.i
.PHONY : source/src/rendermodel.cpp.i

source/src/rendermodel.s: source/src/rendermodel.cpp.s

.PHONY : source/src/rendermodel.s

# target to generate assembly for a file
source/src/rendermodel.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendermodel.cpp.s
.PHONY : source/src/rendermodel.cpp.s

source/src/renderparticles.o: source/src/renderparticles.cpp.o

.PHONY : source/src/renderparticles.o

# target to build an object file
source/src/renderparticles.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/renderparticles.cpp.o
.PHONY : source/src/renderparticles.cpp.o

source/src/renderparticles.i: source/src/renderparticles.cpp.i

.PHONY : source/src/renderparticles.i

# target to preprocess a source file
source/src/renderparticles.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/renderparticles.cpp.i
.PHONY : source/src/renderparticles.cpp.i

source/src/renderparticles.s: source/src/renderparticles.cpp.s

.PHONY : source/src/renderparticles.s

# target to generate assembly for a file
source/src/renderparticles.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/renderparticles.cpp.s
.PHONY : source/src/renderparticles.cpp.s

source/src/rendertext.o: source/src/rendertext.cpp.o

.PHONY : source/src/rendertext.o

# target to build an object file
source/src/rendertext.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendertext.cpp.o
.PHONY : source/src/rendertext.cpp.o

source/src/rendertext.i: source/src/rendertext.cpp.i

.PHONY : source/src/rendertext.i

# target to preprocess a source file
source/src/rendertext.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendertext.cpp.i
.PHONY : source/src/rendertext.cpp.i

source/src/rendertext.s: source/src/rendertext.cpp.s

.PHONY : source/src/rendertext.s

# target to generate assembly for a file
source/src/rendertext.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/rendertext.cpp.s
.PHONY : source/src/rendertext.cpp.s

source/src/scoreboard.o: source/src/scoreboard.cpp.o

.PHONY : source/src/scoreboard.o

# target to build an object file
source/src/scoreboard.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/scoreboard.cpp.o
.PHONY : source/src/scoreboard.cpp.o

source/src/scoreboard.i: source/src/scoreboard.cpp.i

.PHONY : source/src/scoreboard.i

# target to preprocess a source file
source/src/scoreboard.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/scoreboard.cpp.i
.PHONY : source/src/scoreboard.cpp.i

source/src/scoreboard.s: source/src/scoreboard.cpp.s

.PHONY : source/src/scoreboard.s

# target to generate assembly for a file
source/src/scoreboard.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/scoreboard.cpp.s
.PHONY : source/src/scoreboard.cpp.s

source/src/server.o: source/src/server.cpp.o

.PHONY : source/src/server.o

# target to build an object file
source/src/server.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/server.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/server.cpp.o
.PHONY : source/src/server.cpp.o

source/src/server.i: source/src/server.cpp.i

.PHONY : source/src/server.i

# target to preprocess a source file
source/src/server.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/server.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/server.cpp.i
.PHONY : source/src/server.cpp.i

source/src/server.s: source/src/server.cpp.s

.PHONY : source/src/server.s

# target to generate assembly for a file
source/src/server.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/server.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/server.cpp.s
.PHONY : source/src/server.cpp.s

source/src/serverbrowser.o: source/src/serverbrowser.cpp.o

.PHONY : source/src/serverbrowser.o

# target to build an object file
source/src/serverbrowser.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/serverbrowser.cpp.o
.PHONY : source/src/serverbrowser.cpp.o

source/src/serverbrowser.i: source/src/serverbrowser.cpp.i

.PHONY : source/src/serverbrowser.i

# target to preprocess a source file
source/src/serverbrowser.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/serverbrowser.cpp.i
.PHONY : source/src/serverbrowser.cpp.i

source/src/serverbrowser.s: source/src/serverbrowser.cpp.s

.PHONY : source/src/serverbrowser.s

# target to generate assembly for a file
source/src/serverbrowser.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/serverbrowser.cpp.s
.PHONY : source/src/serverbrowser.cpp.s

source/src/serverms.o: source/src/serverms.cpp.o

.PHONY : source/src/serverms.o

# target to build an object file
source/src/serverms.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/serverms.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/serverms.cpp.o
.PHONY : source/src/serverms.cpp.o

source/src/serverms.i: source/src/serverms.cpp.i

.PHONY : source/src/serverms.i

# target to preprocess a source file
source/src/serverms.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/serverms.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/serverms.cpp.i
.PHONY : source/src/serverms.cpp.i

source/src/serverms.s: source/src/serverms.cpp.s

.PHONY : source/src/serverms.s

# target to generate assembly for a file
source/src/serverms.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/serverms.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/serverms.cpp.s
.PHONY : source/src/serverms.cpp.s

source/src/shadow.o: source/src/shadow.cpp.o

.PHONY : source/src/shadow.o

# target to build an object file
source/src/shadow.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/shadow.cpp.o
.PHONY : source/src/shadow.cpp.o

source/src/shadow.i: source/src/shadow.cpp.i

.PHONY : source/src/shadow.i

# target to preprocess a source file
source/src/shadow.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/shadow.cpp.i
.PHONY : source/src/shadow.cpp.i

source/src/shadow.s: source/src/shadow.cpp.s

.PHONY : source/src/shadow.s

# target to generate assembly for a file
source/src/shadow.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/shadow.cpp.s
.PHONY : source/src/shadow.cpp.s

source/src/sound.o: source/src/sound.cpp.o

.PHONY : source/src/sound.o

# target to build an object file
source/src/sound.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/sound.cpp.o
.PHONY : source/src/sound.cpp.o

source/src/sound.i: source/src/sound.cpp.i

.PHONY : source/src/sound.i

# target to preprocess a source file
source/src/sound.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/sound.cpp.i
.PHONY : source/src/sound.cpp.i

source/src/sound.s: source/src/sound.cpp.s

.PHONY : source/src/sound.s

# target to generate assembly for a file
source/src/sound.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/sound.cpp.s
.PHONY : source/src/sound.cpp.s

source/src/soundlocation.o: source/src/soundlocation.cpp.o

.PHONY : source/src/soundlocation.o

# target to build an object file
source/src/soundlocation.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/soundlocation.cpp.o
.PHONY : source/src/soundlocation.cpp.o

source/src/soundlocation.i: source/src/soundlocation.cpp.i

.PHONY : source/src/soundlocation.i

# target to preprocess a source file
source/src/soundlocation.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/soundlocation.cpp.i
.PHONY : source/src/soundlocation.cpp.i

source/src/soundlocation.s: source/src/soundlocation.cpp.s

.PHONY : source/src/soundlocation.s

# target to generate assembly for a file
source/src/soundlocation.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/soundlocation.cpp.s
.PHONY : source/src/soundlocation.cpp.s

source/src/soundscheduler.o: source/src/soundscheduler.cpp.o

.PHONY : source/src/soundscheduler.o

# target to build an object file
source/src/soundscheduler.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/soundscheduler.cpp.o
.PHONY : source/src/soundscheduler.cpp.o

source/src/soundscheduler.i: source/src/soundscheduler.cpp.i

.PHONY : source/src/soundscheduler.i

# target to preprocess a source file
source/src/soundscheduler.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/soundscheduler.cpp.i
.PHONY : source/src/soundscheduler.cpp.i

source/src/soundscheduler.s: source/src/soundscheduler.cpp.s

.PHONY : source/src/soundscheduler.s

# target to generate assembly for a file
source/src/soundscheduler.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/soundscheduler.cpp.s
.PHONY : source/src/soundscheduler.cpp.s

source/src/stream.o: source/src/stream.cpp.o

.PHONY : source/src/stream.o

# target to build an object file
source/src/stream.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/stream.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/stream.cpp.o
.PHONY : source/src/stream.cpp.o

source/src/stream.i: source/src/stream.cpp.i

.PHONY : source/src/stream.i

# target to preprocess a source file
source/src/stream.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/stream.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/stream.cpp.i
.PHONY : source/src/stream.cpp.i

source/src/stream.s: source/src/stream.cpp.s

.PHONY : source/src/stream.s

# target to generate assembly for a file
source/src/stream.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/stream.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/stream.cpp.s
.PHONY : source/src/stream.cpp.s

source/src/texture.o: source/src/texture.cpp.o

.PHONY : source/src/texture.o

# target to build an object file
source/src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/texture.cpp.o
.PHONY : source/src/texture.cpp.o

source/src/texture.i: source/src/texture.cpp.i

.PHONY : source/src/texture.i

# target to preprocess a source file
source/src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/texture.cpp.i
.PHONY : source/src/texture.cpp.i

source/src/texture.s: source/src/texture.cpp.s

.PHONY : source/src/texture.s

# target to generate assembly for a file
source/src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/texture.cpp.s
.PHONY : source/src/texture.cpp.s

source/src/tools.o: source/src/tools.cpp.o

.PHONY : source/src/tools.o

# target to build an object file
source/src/tools.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/tools.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/tools.cpp.o
.PHONY : source/src/tools.cpp.o

source/src/tools.i: source/src/tools.cpp.i

.PHONY : source/src/tools.i

# target to preprocess a source file
source/src/tools.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/tools.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/tools.cpp.i
.PHONY : source/src/tools.cpp.i

source/src/tools.s: source/src/tools.cpp.s

.PHONY : source/src/tools.s

# target to generate assembly for a file
source/src/tools.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/tools.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/tools.cpp.s
.PHONY : source/src/tools.cpp.s

source/src/water.o: source/src/water.cpp.o

.PHONY : source/src/water.o

# target to build an object file
source/src/water.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/water.cpp.o
.PHONY : source/src/water.cpp.o

source/src/water.i: source/src/water.cpp.i

.PHONY : source/src/water.i

# target to preprocess a source file
source/src/water.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/water.cpp.i
.PHONY : source/src/water.cpp.i

source/src/water.s: source/src/water.cpp.s

.PHONY : source/src/water.s

# target to generate assembly for a file
source/src/water.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/water.cpp.s
.PHONY : source/src/water.cpp.s

source/src/weapon.o: source/src/weapon.cpp.o

.PHONY : source/src/weapon.o

# target to build an object file
source/src/weapon.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/weapon.cpp.o
.PHONY : source/src/weapon.cpp.o

source/src/weapon.i: source/src/weapon.cpp.i

.PHONY : source/src/weapon.i

# target to preprocess a source file
source/src/weapon.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/weapon.cpp.i
.PHONY : source/src/weapon.cpp.i

source/src/weapon.s: source/src/weapon.cpp.s

.PHONY : source/src/weapon.s

# target to generate assembly for a file
source/src/weapon.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/weapon.cpp.s
.PHONY : source/src/weapon.cpp.s

source/src/wizard.o: source/src/wizard.cpp.o

.PHONY : source/src/wizard.o

# target to build an object file
source/src/wizard.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/wizard.cpp.o
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/wizard.cpp.o
.PHONY : source/src/wizard.cpp.o

source/src/wizard.i: source/src/wizard.cpp.i

.PHONY : source/src/wizard.i

# target to preprocess a source file
source/src/wizard.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/wizard.cpp.i
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/wizard.cpp.i
.PHONY : source/src/wizard.cpp.i

source/src/wizard.s: source/src/wizard.cpp.s

.PHONY : source/src/wizard.s

# target to generate assembly for a file
source/src/wizard.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/wizard.cpp.s
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/source/src/wizard.cpp.s
.PHONY : source/src/wizard.cpp.s

source/src/world.o: source/src/world.cpp.o

.PHONY : source/src/world.o

# target to build an object file
source/src/world.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/world.cpp.o
.PHONY : source/src/world.cpp.o

source/src/world.i: source/src/world.cpp.i

.PHONY : source/src/world.i

# target to preprocess a source file
source/src/world.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/world.cpp.i
.PHONY : source/src/world.cpp.i

source/src/world.s: source/src/world.cpp.s

.PHONY : source/src/world.s

# target to generate assembly for a file
source/src/world.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/world.cpp.s
.PHONY : source/src/world.cpp.s

source/src/worldio.o: source/src/worldio.cpp.o

.PHONY : source/src/worldio.o

# target to build an object file
source/src/worldio.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldio.cpp.o
.PHONY : source/src/worldio.cpp.o

source/src/worldio.i: source/src/worldio.cpp.i

.PHONY : source/src/worldio.i

# target to preprocess a source file
source/src/worldio.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldio.cpp.i
.PHONY : source/src/worldio.cpp.i

source/src/worldio.s: source/src/worldio.cpp.s

.PHONY : source/src/worldio.s

# target to generate assembly for a file
source/src/worldio.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldio.cpp.s
.PHONY : source/src/worldio.cpp.s

source/src/worldlight.o: source/src/worldlight.cpp.o

.PHONY : source/src/worldlight.o

# target to build an object file
source/src/worldlight.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldlight.cpp.o
.PHONY : source/src/worldlight.cpp.o

source/src/worldlight.i: source/src/worldlight.cpp.i

.PHONY : source/src/worldlight.i

# target to preprocess a source file
source/src/worldlight.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldlight.cpp.i
.PHONY : source/src/worldlight.cpp.i

source/src/worldlight.s: source/src/worldlight.cpp.s

.PHONY : source/src/worldlight.s

# target to generate assembly for a file
source/src/worldlight.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldlight.cpp.s
.PHONY : source/src/worldlight.cpp.s

source/src/worldocull.o: source/src/worldocull.cpp.o

.PHONY : source/src/worldocull.o

# target to build an object file
source/src/worldocull.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldocull.cpp.o
.PHONY : source/src/worldocull.cpp.o

source/src/worldocull.i: source/src/worldocull.cpp.i

.PHONY : source/src/worldocull.i

# target to preprocess a source file
source/src/worldocull.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldocull.cpp.i
.PHONY : source/src/worldocull.cpp.i

source/src/worldocull.s: source/src/worldocull.cpp.s

.PHONY : source/src/worldocull.s

# target to generate assembly for a file
source/src/worldocull.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldocull.cpp.s
.PHONY : source/src/worldocull.cpp.s

source/src/worldrender.o: source/src/worldrender.cpp.o

.PHONY : source/src/worldrender.o

# target to build an object file
source/src/worldrender.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldrender.cpp.o
.PHONY : source/src/worldrender.cpp.o

source/src/worldrender.i: source/src/worldrender.cpp.i

.PHONY : source/src/worldrender.i

# target to preprocess a source file
source/src/worldrender.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldrender.cpp.i
.PHONY : source/src/worldrender.cpp.i

source/src/worldrender.s: source/src/worldrender.cpp.s

.PHONY : source/src/worldrender.s

# target to generate assembly for a file
source/src/worldrender.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/worldrender.cpp.s
.PHONY : source/src/worldrender.cpp.s

source/src/zip.o: source/src/zip.cpp.o

.PHONY : source/src/zip.o

# target to build an object file
source/src/zip.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/zip.cpp.o
.PHONY : source/src/zip.cpp.o

source/src/zip.i: source/src/zip.cpp.i

.PHONY : source/src/zip.i

# target to preprocess a source file
source/src/zip.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/zip.cpp.i
.PHONY : source/src/zip.cpp.i

source/src/zip.s: source/src/zip.cpp.s

.PHONY : source/src/zip.s

# target to generate assembly for a file
source/src/zip.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/source/src/zip.cpp.s
.PHONY : source/src/zip.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... client"
	@echo "... clean-enet"
	@echo "... enet"
	@echo "... enet-config"
	@echo "... source/src/audiomanager.o"
	@echo "... source/src/audiomanager.i"
	@echo "... source/src/audiomanager.s"
	@echo "... source/src/bot/ac_bot.o"
	@echo "... source/src/bot/ac_bot.i"
	@echo "... source/src/bot/ac_bot.s"
	@echo "... source/src/bot/ac_bot_ai.o"
	@echo "... source/src/bot/ac_bot_ai.i"
	@echo "... source/src/bot/ac_bot_ai.s"
	@echo "... source/src/bot/bot.o"
	@echo "... source/src/bot/bot.i"
	@echo "... source/src/bot/bot.s"
	@echo "... source/src/bot/bot_ai.o"
	@echo "... source/src/bot/bot_ai.i"
	@echo "... source/src/bot/bot_ai.s"
	@echo "... source/src/bot/bot_util.o"
	@echo "... source/src/bot/bot_util.i"
	@echo "... source/src/bot/bot_util.s"
	@echo "... source/src/bot/bot_waypoint.o"
	@echo "... source/src/bot/bot_waypoint.i"
	@echo "... source/src/bot/bot_waypoint.s"
	@echo "... source/src/bot/botmanager.o"
	@echo "... source/src/bot/botmanager.i"
	@echo "... source/src/bot/botmanager.s"
	@echo "... source/src/client.o"
	@echo "... source/src/client.i"
	@echo "... source/src/client.s"
	@echo "... source/src/clientgame.o"
	@echo "... source/src/clientgame.i"
	@echo "... source/src/clientgame.s"
	@echo "... source/src/clients2c.o"
	@echo "... source/src/clients2c.i"
	@echo "... source/src/clients2c.s"
	@echo "... source/src/command.o"
	@echo "... source/src/command.i"
	@echo "... source/src/command.s"
	@echo "... source/src/console.o"
	@echo "... source/src/console.i"
	@echo "... source/src/console.s"
	@echo "... source/src/crypto.o"
	@echo "... source/src/crypto.i"
	@echo "... source/src/crypto.s"
	@echo "... source/src/docs.o"
	@echo "... source/src/docs.i"
	@echo "... source/src/docs.s"
	@echo "... source/src/dummy.o"
	@echo "... source/src/dummy.i"
	@echo "... source/src/dummy.s"
	@echo "... source/src/editing.o"
	@echo "... source/src/editing.i"
	@echo "... source/src/editing.s"
	@echo "... source/src/entities.o"
	@echo "... source/src/entities.i"
	@echo "... source/src/entities.s"
	@echo "... source/src/geom.o"
	@echo "... source/src/geom.i"
	@echo "... source/src/geom.s"
	@echo "... source/src/i18n.o"
	@echo "... source/src/i18n.i"
	@echo "... source/src/i18n.s"
	@echo "... source/src/jpegenc.o"
	@echo "... source/src/jpegenc.i"
	@echo "... source/src/jpegenc.s"
	@echo "... source/src/log.o"
	@echo "... source/src/log.i"
	@echo "... source/src/log.s"
	@echo "... source/src/main.o"
	@echo "... source/src/main.i"
	@echo "... source/src/main.s"
	@echo "... source/src/menus.o"
	@echo "... source/src/menus.i"
	@echo "... source/src/menus.s"
	@echo "... source/src/physics.o"
	@echo "... source/src/physics.i"
	@echo "... source/src/physics.s"
	@echo "... source/src/protocol.o"
	@echo "... source/src/protocol.i"
	@echo "... source/src/protocol.s"
	@echo "... source/src/rendercubes.o"
	@echo "... source/src/rendercubes.i"
	@echo "... source/src/rendercubes.s"
	@echo "... source/src/rendergl.o"
	@echo "... source/src/rendergl.i"
	@echo "... source/src/rendergl.s"
	@echo "... source/src/renderhud.o"
	@echo "... source/src/renderhud.i"
	@echo "... source/src/renderhud.s"
	@echo "... source/src/rendermodel.o"
	@echo "... source/src/rendermodel.i"
	@echo "... source/src/rendermodel.s"
	@echo "... source/src/renderparticles.o"
	@echo "... source/src/renderparticles.i"
	@echo "... source/src/renderparticles.s"
	@echo "... source/src/rendertext.o"
	@echo "... source/src/rendertext.i"
	@echo "... source/src/rendertext.s"
	@echo "... source/src/scoreboard.o"
	@echo "... source/src/scoreboard.i"
	@echo "... source/src/scoreboard.s"
	@echo "... source/src/server.o"
	@echo "... source/src/server.i"
	@echo "... source/src/server.s"
	@echo "... source/src/serverbrowser.o"
	@echo "... source/src/serverbrowser.i"
	@echo "... source/src/serverbrowser.s"
	@echo "... source/src/serverms.o"
	@echo "... source/src/serverms.i"
	@echo "... source/src/serverms.s"
	@echo "... source/src/shadow.o"
	@echo "... source/src/shadow.i"
	@echo "... source/src/shadow.s"
	@echo "... source/src/sound.o"
	@echo "... source/src/sound.i"
	@echo "... source/src/sound.s"
	@echo "... source/src/soundlocation.o"
	@echo "... source/src/soundlocation.i"
	@echo "... source/src/soundlocation.s"
	@echo "... source/src/soundscheduler.o"
	@echo "... source/src/soundscheduler.i"
	@echo "... source/src/soundscheduler.s"
	@echo "... source/src/stream.o"
	@echo "... source/src/stream.i"
	@echo "... source/src/stream.s"
	@echo "... source/src/texture.o"
	@echo "... source/src/texture.i"
	@echo "... source/src/texture.s"
	@echo "... source/src/tools.o"
	@echo "... source/src/tools.i"
	@echo "... source/src/tools.s"
	@echo "... source/src/water.o"
	@echo "... source/src/water.i"
	@echo "... source/src/water.s"
	@echo "... source/src/weapon.o"
	@echo "... source/src/weapon.i"
	@echo "... source/src/weapon.s"
	@echo "... source/src/wizard.o"
	@echo "... source/src/wizard.i"
	@echo "... source/src/wizard.s"
	@echo "... source/src/world.o"
	@echo "... source/src/world.i"
	@echo "... source/src/world.s"
	@echo "... source/src/worldio.o"
	@echo "... source/src/worldio.i"
	@echo "... source/src/worldio.s"
	@echo "... source/src/worldlight.o"
	@echo "... source/src/worldlight.i"
	@echo "... source/src/worldlight.s"
	@echo "... source/src/worldocull.o"
	@echo "... source/src/worldocull.i"
	@echo "... source/src/worldocull.s"
	@echo "... source/src/worldrender.o"
	@echo "... source/src/worldrender.i"
	@echo "... source/src/worldrender.s"
	@echo "... source/src/zip.o"
	@echo "... source/src/zip.i"
	@echo "... source/src/zip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

